name: Wine Ubuntu NTSYNC CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:rolling

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          dpkg --add-architecture i386 && apt update
          apt install -y aptitude linux-libc-dev
          aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-git 
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          sed -i 's/_use_ntsync=\"false\"/_use_ntsync=\"true\"/' customization.cfg
          sed -i 's/_use_esync=\"true\"/_use_esync=\"false\"/' customization.cfg
          sed -i 's/_use_fsync=\"true\"/_use_fsync=\"false\"/' customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
